config/routes.rb
Howto::Application.routes.draw do

  resources :tasks do
    resources :steps
  end
  root 'welcome#index'

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :task
  validates :task, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # before_action :load_task

  def index
    @task = Task.find(params[:task_id])
    # @steps = Step.find(params[:id])
    # @tasksteps = task_steps_path(@task)
  end

  def new
    @task = Task.find(params[:task_id])
    @step = @task.steps.new
  end

  def create
    @task = Task.find(params[:task_id])
    @step = @task.steps.new(step_params)
    if @step.save
      flash[:success] = "Step added!"
      redirect_to task_path(@task)
    else
      flash[:error] = "Uh oh, step not added"
      render 'new'
    end
  end

  def show
    @step = Step.find(params[:id])
  end

  def edit
  end

def destroy
  @step = Step.find(params[:id]).destroy
  redirect_to task_path
end

  private


  def load_task
    @task = Task.find(params[:id])
  end

  def step_params
    params.require(:step).permit(:title, :note, :task_id)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
     @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:notice] = "New task added - get to work!"
      redirect_to @task
    else
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
    # task_path
  end

  def edit
  end

  def destroy
    @task = Task.find(params[:id]).destroy
    redirect_to task_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :difficulty)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howto</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
  <div class="alert flash <%= type %>">
    <%= message %>
  </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/steps/edit.html.erb
<h1>Steps#edit</h1>
<p>Find me in app/views/steps/edit.html.erb</p>

app/views/steps/index.html.erb
<%= link_to "[All Tasks]", tasks_path %><br />
add step [<%= link_to "+", new_task_step_path %>]<br /><br />
Task: <%= link_to @task.title, task_path(@task) %>
now has (<%= pluralize(@task.steps.count, "step") %>)

app/views/steps/new.html.erb
<h1>Create a new step...</h1>

<%= form_for [@task, @step] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.submit "Submit" %>
<% end %>

app/views/steps/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "task", @task %>

    <ul><%= @step.title %>
      <li>
      </li>
    </ul>

app/views/tasks/_form.html.erb
<h1>Tasks#_form</h1>
<p>Find me in app/views/tasks/_form.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h3>All Tasks</h3>
add task [<%= link_to "+", new_task_path %>]<br /><br />


<% @tasks.each do |task| %>
  <ul>
    <li>
      <%= link_to task.title, task %> (<%= task.steps.count %>)
      <%= link_to "Delete", task, action: "delete", method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  </ul>
  <% end %>

app/views/tasks/new.html.erb
<h3>New Task</h3>
<%= link_to "<< back to tasks", tasks_path %><br /><br />

<%= form_for @task do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.submit "Submit" %>
<% end %>

app/views/tasks/show.html.erb
<%#= tweet.author.downcase %>
  <%#= highlight(simple_format(word_wrap(truncate(tweet.body, length: 80) { link_to "(read more)", tweet })), @query) %>
<table>
  <tr>
    <td><%= link_to "[All Tasks]", tasks_path %></td>
    <td></td>
    <td></td>
    <td></td>
    <td>Created on <%= @task.created_at.getlocal.strftime("%D") %></td>
  </tr>
  <tr>
    <td>add step [<%= link_to "+", new_task_step_path(@task) %>]</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
  </tr>
  <tr>
    <th></th>
    <th><h4><%= @task.title %></h4></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>edit </td>
    <td>delete</td>
    <td></td>
  </tr>
  <tr>
    <% @task.steps.each do |step| %>
    <td><%= step.title %></td>
    <td></td>
    <td>[!]
    </td>
    <td></td>
    <td><%= link_to "[x]", task_step_path(@task, step), action: "delete", method: :delete, data: { confirm: "Are you sure?" } %></td>

  </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h4>Welcome</h4>
Tasks (<a href="<%= tasks_path %>"><%= Task.count %></a>)<br />
add [<%= link_to "+", new_task_path %>]<br /><br />

A total of <%= pluralize(Step.count, "step") %> has been created.